on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "You've successfully pushed some content to branch master!"